## @package request_handler
# Parse request environments generated by uwsgi

from urlparse import parse_qs
import db_interface as db
import plot
import json

TMP_PLOT_NAME = 'Usage_Plot.png'

##
# @param d dictionary to check for args
# @param args args to check for in the dictionary
# @return True if d contains entries for all args. False otherwise
def dict_contains(d, *args):
    ''' return True if all args are in d '''
    for arg in args:
        if arg not in d:
            return False
    return True

##
# @param env The environment parameter generated by uwsgi
# @return A tuple containing two values. If env is a valid file request, the
# first element in the tuple is True and the second is the contents of the
# file. If it's not a valid file request, (False, None).
def handle_file_request(env):
    req_uri = env['REQUEST_URI']
    if len(req_uri) > 1 and '?' not in req_uri:
        filename = req_uri[1:]
        try:
            ret = open(filename).read()
        except:
            ret = ''
        return (True, ret)
    return (False, None)

##
# @param env The environment parameter generated by uwsgi
# @return If the request is a GET request, (True, page contents). Otherwise,
# (False, None)
#
# There are two valid effectful GET requests, with the following parameters:
#   insert, timestamp, usage
#   query, timestamp
# insert and query are the valid operations with parameters timestamp and usage
# or just timestamp
def handle_get_request(env):
    queries = parse_qs(env['QUERY_STRING'])
    if dict_contains(queries, 'insert', 'timestamp', 'usage'):
        ts = queries['timestamp'][0]
        usage = queries['usage'][0]
        db.add_row(ts, usage)
        ret = '<p>Inserted row: timestamp = {}, usage = {}</p>'.format(ts, usage)
        return (True, ret)
    elif dict_contains(queries, 'query', 'timestamp'):
        query = db.query_by_timestamp(int(queries['timestamp'][0]))
        timestamps = []
        usage = []
        for val in query:
            timestamps.append(int(val[0]))
            usage.append(int(val[1]))
        plot.make_plot(timestamps, usage)
        ret = "<img src='{}' alt='plot' />".format(TMP_PLOT_NAME)
        return (True, ret)
    return (False, None)

##
# @param env The environment parameter generated by uwsgi
# @return If the request is a POST request with a non-empty body, (True,
# request body), otherwise (False, None)
#
# If the request is JSON format with fields function, usage, and timestamp, and
# the function field has the value 'insert', create a row in the default
# database
def handle_post_request(env):
    try:
        req_body_length = int(env.get('CONTENT_LENGTH', 0))
    except (ValueError):
        req_body_length = 0
    if req_body_length:
        req_body = json.loads(env['wsgi.input'].read(req_body_length))
        try:
            if req_body['function'] == 'insert':
                usage = req_body['usage']
                ts = req_body['timestamp']
                db.add_row(ts, usage)
        except:
            pass
        finally:
            return (True, req_body)
    return (False, None)

